# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/devosophy',
                'doc_host': 'https://deven367.github.io',
                'git_url': 'https://github.com/deven367/devosophy',
                'lib_path': 'devosophy'},
  'syms': {'devosophy.core': {'devosophy.core.foo': ('core.html#foo', 'devosophy/core.py')}}}
