"""The data module for the library"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/data.ipynb.

# %% auto 0
__all__ = ['DatasetWithStride']

# %% ../nbs/data.ipynb 2
import torch
from torch.utils.data import Dataset
from typing import Tuple

from fastcore.foundation import patch

# %% ../nbs/data.ipynb 3
class DatasetWithStride(
    Dataset, # torch dataset
    ):
    """Expects tokenized text, block size and stride
    """
    def __init__(self, data, block_size, stride):
        self.data = data
        self.block_size = block_size
        self.stride = stride
        self.num_samples = (len(data) - block_size) // stride


# %% ../nbs/data.ipynb 4
@patch
def __len__(self: DatasetWithStride):
    return self.num_samples

# %% ../nbs/data.ipynb 5
@patch
def __getitem__(self:DatasetWithStride, idx)->Tuple[torch.tensor, torch.tensor]:
    start_idx = idx * self.stride

    chunk = self.data[start_idx : start_idx + self.block_size + 1]
    x = chunk[:-1]
    y = chunk[1:]
    # print(idx, chunk.shape, x.shape, y.shape)
    return x, y
